<?php

use Illuminate\Database\Seeder;

use App\Models\Guiaproduccion as Guiaproduccion;

class GuiaproduccionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      Guiaproduccion::create([
          'semanaGup' => '1',
          'tbGup' => '1',
          'tb1Gup' => '2',
          'tb2Gup' => '3',
          'real4Gup' => '4',
          'tab1Gup' => '5',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '2',
          'tbGup' => '6',
          'tb1Gup' => '7',
          'tb2Gup' => '8',
          'real4Gup' => '9',
          'tab1Gup' => '10',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '3',
          'tbGup' => '11',
          'tb1Gup' => '12',
          'tb2Gup' => '13',
          'real4Gup' => '14',
          'tab1Gup' => '15',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '4',
          'tbGup' => '16',
          'tb1Gup' => '17',
          'tb2Gup' => '18',
          'real4Gup' => '19',
          'tab1Gup' => '20',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '5',
          'tbGup' => '21',
          'tb1Gup' => '22',
          'tb2Gup' => '23',
          'real4Gup' => '24',
          'tab1Gup' => '25',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '6',
          'tbGup' => '26',
          'tb1Gup' => '27',
          'tb2Gup' => '28',
          'real4Gup' => '29',
          'tab1Gup' => '30',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '7',
          'tbGup' => '31',
          'tb1Gup' => '32',
          'tb2Gup' => '33',
          'real4Gup' => '34',
          'tab1Gup' => '35',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '8',
          'tbGup' => '36',
          'tb1Gup' => '37',
          'tb2Gup' => '38',
          'real4Gup' => '39',
          'tab1Gup' => '40',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '9',
          'tbGup' => '41',
          'tb1Gup' => '42',
          'tb2Gup' => '43',
          'real4Gup' => '44',
          'tab1Gup' => '45',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '10',
          'tbGup' => '46',
          'tb1Gup' => '47',
          'tb2Gup' => '48',
          'real4Gup' => '49',
          'tab1Gup' => '50',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '11',
          'tbGup' => '51',
          'tb1Gup' => '52',
          'tb2Gup' => '53',
          'real4Gup' => '54',
          'tab1Gup' => '55',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '12',
          'tbGup' => '56',
          'tb1Gup' => '57',
          'tb2Gup' => '58',
          'real4Gup' => '59',
          'tab1Gup' => '60',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '13',
          'tbGup' => '61',
          'tb1Gup' => '62',
          'tb2Gup' => '63',
          'real4Gup' => '64',
          'tab1Gup' => '65',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '14',
          'tbGup' => '66',
          'tb1Gup' => '67',
          'tb2Gup' => '68',
          'real4Gup' => '69',
          'tab1Gup' => '70',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '15',
          'tbGup' => '71',
          'tb1Gup' => '72',
          'tb2Gup' => '73',
          'real4Gup' => '74',
          'tab1Gup' => '75',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '16',
          'tbGup' => '76',
          'tb1Gup' => '77',
          'tb2Gup' => '78',
          'real4Gup' => '79',
          'tab1Gup' => '80',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '17',
          'tbGup' => '81',
          'tb1Gup' => '82',
          'tb2Gup' => '83',
          'real4Gup' => '84',
          'tab1Gup' => '85',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '18',
          'tbGup' => '1',
          'tb1Gup' => '2',
          'tb2Gup' => '3',
          'real4Gup' => '4',
          'tab1Gup' => '5',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '19',
          'tbGup' => '6',
          'tb1Gup' => '7',
          'tb2Gup' => '8',
          'real4Gup' => '9',
          'tab1Gup' => '10',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '20',
          'tbGup' => '11',
          'tb1Gup' => '12',
          'tb2Gup' => '13',
          'real4Gup' => '14',
          'tab1Gup' => '15',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '21',
          'tbGup' => '16',
          'tb1Gup' => '17',
          'tb2Gup' => '18',
          'real4Gup' => '19',
          'tab1Gup' => '20',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '22',
          'tbGup' => '21',
          'tb1Gup' => '22',
          'tb2Gup' => '23',
          'real4Gup' => '24',
          'tab1Gup' => '25',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '23',
          'tbGup' => '26',
          'tb1Gup' => '27',
          'tb2Gup' => '28',
          'real4Gup' => '29',
          'tab1Gup' => '30',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '24',
          'tbGup' => '31',
          'tb1Gup' => '32',
          'tb2Gup' => '33',
          'real4Gup' => '34',
          'tab1Gup' => '35',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '25',
          'tbGup' => '36',
          'tb1Gup' => '37',
          'tb2Gup' => '38',
          'real4Gup' => '39',
          'tab1Gup' => '40',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '26',
          'tbGup' => '41',
          'tb1Gup' => '42',
          'tb2Gup' => '43',
          'real4Gup' => '44',
          'tab1Gup' => '45',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '27',
          'tbGup' => '46',
          'tb1Gup' => '47',
          'tb2Gup' => '48',
          'real4Gup' => '49',
          'tab1Gup' => '50',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '28',
          'tbGup' => '51',
          'tb1Gup' => '52',
          'tb2Gup' => '53',
          'real4Gup' => '54',
          'tab1Gup' => '55',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '29',
          'tbGup' => '56',
          'tb1Gup' => '57',
          'tb2Gup' => '58',
          'real4Gup' => '59',
          'tab1Gup' => '60',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '30',
          'tbGup' => '61',
          'tb1Gup' => '62',
          'tb2Gup' => '63',
          'real4Gup' => '64',
          'tab1Gup' => '65',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '31',
          'tbGup' => '66',
          'tb1Gup' => '67',
          'tb2Gup' => '68',
          'real4Gup' => '69',
          'tab1Gup' => '70',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '32',
          'tbGup' => '71',
          'tb1Gup' => '72',
          'tb2Gup' => '73',
          'real4Gup' => '74',
          'tab1Gup' => '75',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '33',
          'tbGup' => '76',
          'tb1Gup' => '77',
          'tb2Gup' => '78',
          'real4Gup' => '79',
          'tab1Gup' => '80',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '34',
          'tbGup' => '81',
          'tb1Gup' => '82',
          'tb2Gup' => '83',
          'real4Gup' => '84',
          'tab1Gup' => '85',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '35',
          'tbGup' => '1',
          'tb1Gup' => '2',
          'tb2Gup' => '3',
          'real4Gup' => '4',
          'tab1Gup' => '5',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '36',
          'tbGup' => '6',
          'tb1Gup' => '7',
          'tb2Gup' => '8',
          'real4Gup' => '9',
          'tab1Gup' => '10',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '37',
          'tbGup' => '11',
          'tb1Gup' => '12',
          'tb2Gup' => '13',
          'real4Gup' => '14',
          'tab1Gup' => '15',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '38',
          'tbGup' => '16',
          'tb1Gup' => '17',
          'tb2Gup' => '18',
          'real4Gup' => '19',
          'tab1Gup' => '20',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '39',
          'tbGup' => '21',
          'tb1Gup' => '22',
          'tb2Gup' => '23',
          'real4Gup' => '24',
          'tab1Gup' => '25',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '40',
          'tbGup' => '26',
          'tb1Gup' => '27',
          'tb2Gup' => '28',
          'real4Gup' => '29',
          'tab1Gup' => '30',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '41',
          'tbGup' => '31',
          'tb1Gup' => '32',
          'tb2Gup' => '33',
          'real4Gup' => '34',
          'tab1Gup' => '35',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '42',
          'tbGup' => '36',
          'tb1Gup' => '37',
          'tb2Gup' => '38',
          'real4Gup' => '39',
          'tab1Gup' => '40',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '43',
          'tbGup' => '41',
          'tb1Gup' => '42',
          'tb2Gup' => '43',
          'real4Gup' => '44',
          'tab1Gup' => '45',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '44',
          'tbGup' => '46',
          'tb1Gup' => '47',
          'tb2Gup' => '48',
          'real4Gup' => '49',
          'tab1Gup' => '50',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '45',
          'tbGup' => '51',
          'tb1Gup' => '52',
          'tb2Gup' => '53',
          'real4Gup' => '54',
          'tab1Gup' => '55',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '46',
          'tbGup' => '56',
          'tb1Gup' => '57',
          'tb2Gup' => '58',
          'real4Gup' => '59',
          'tab1Gup' => '60',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '47',
          'tbGup' => '61',
          'tb1Gup' => '62',
          'tb2Gup' => '63',
          'real4Gup' => '64',
          'tab1Gup' => '65',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '48',
          'tbGup' => '66',
          'tb1Gup' => '67',
          'tb2Gup' => '68',
          'real4Gup' => '69',
          'tab1Gup' => '70',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '49',
          'tbGup' => '71',
          'tb1Gup' => '72',
          'tb2Gup' => '73',
          'real4Gup' => '74',
          'tab1Gup' => '75',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '50',
          'tbGup' => '76',
          'tb1Gup' => '77',
          'tb2Gup' => '78',
          'real4Gup' => '79',
          'tab1Gup' => '80',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '51',
          'tbGup' => '81',
          'tb1Gup' => '82',
          'tb2Gup' => '83',
          'real4Gup' => '84',
          'tab1Gup' => '85',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '52',
          'tbGup' => '1',
          'tb1Gup' => '2',
          'tb2Gup' => '3',
          'real4Gup' => '4',
          'tab1Gup' => '5',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '53',
          'tbGup' => '6',
          'tb1Gup' => '7',
          'tb2Gup' => '8',
          'real4Gup' => '9',
          'tab1Gup' => '10',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '54',
          'tbGup' => '11',
          'tb1Gup' => '12',
          'tb2Gup' => '13',
          'real4Gup' => '14',
          'tab1Gup' => '15',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '55',
          'tbGup' => '16',
          'tb1Gup' => '17',
          'tb2Gup' => '18',
          'real4Gup' => '19',
          'tab1Gup' => '20',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '56',
          'tbGup' => '21',
          'tb1Gup' => '22',
          'tb2Gup' => '23',
          'real4Gup' => '24',
          'tab1Gup' => '25',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '57',
          'tbGup' => '26',
          'tb1Gup' => '27',
          'tb2Gup' => '28',
          'real4Gup' => '29',
          'tab1Gup' => '30',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '58',
          'tbGup' => '31',
          'tb1Gup' => '32',
          'tb2Gup' => '33',
          'real4Gup' => '34',
          'tab1Gup' => '35',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '59',
          'tbGup' => '36',
          'tb1Gup' => '37',
          'tb2Gup' => '38',
          'real4Gup' => '39',
          'tab1Gup' => '40',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '60',
          'tbGup' => '41',
          'tb1Gup' => '42',
          'tb2Gup' => '43',
          'real4Gup' => '44',
          'tab1Gup' => '45',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '61',
          'tbGup' => '46',
          'tb1Gup' => '47',
          'tb2Gup' => '48',
          'real4Gup' => '49',
          'tab1Gup' => '50',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '62',
          'tbGup' => '51',
          'tb1Gup' => '52',
          'tb2Gup' => '53',
          'real4Gup' => '54',
          'tab1Gup' => '55',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '63',
          'tbGup' => '56',
          'tb1Gup' => '57',
          'tb2Gup' => '58',
          'real4Gup' => '59',
          'tab1Gup' => '60',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '64',
          'tbGup' => '61',
          'tb1Gup' => '62',
          'tb2Gup' => '63',
          'real4Gup' => '64',
          'tab1Gup' => '65',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '65',
          'tbGup' => '66',
          'tb1Gup' => '67',
          'tb2Gup' => '68',
          'real4Gup' => '69',
          'tab1Gup' => '70',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '66',
          'tbGup' => '71',
          'tb1Gup' => '72',
          'tb2Gup' => '73',
          'real4Gup' => '74',
          'tab1Gup' => '75',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '67',
          'tbGup' => '76',
          'tb1Gup' => '77',
          'tb2Gup' => '78',
          'real4Gup' => '79',
          'tab1Gup' => '80',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '68',
          'tbGup' => '81',
          'tb1Gup' => '82',
          'tb2Gup' => '83',
          'real4Gup' => '84',
          'tab1Gup' => '85',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '69',
          'tbGup' => '1',
          'tb1Gup' => '2',
          'tb2Gup' => '3',
          'real4Gup' => '4',
          'tab1Gup' => '5',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '70',
          'tbGup' => '6',
          'tb1Gup' => '7',
          'tb2Gup' => '8',
          'real4Gup' => '9',
          'tab1Gup' => '10',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '71',
          'tbGup' => '11',
          'tb1Gup' => '12',
          'tb2Gup' => '13',
          'real4Gup' => '14',
          'tab1Gup' => '15',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '72',
          'tbGup' => '16',
          'tb1Gup' => '17',
          'tb2Gup' => '18',
          'real4Gup' => '19',
          'tab1Gup' => '20',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '73',
          'tbGup' => '21',
          'tb1Gup' => '22',
          'tb2Gup' => '23',
          'real4Gup' => '24',
          'tab1Gup' => '25',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '74',
          'tbGup' => '26',
          'tb1Gup' => '27',
          'tb2Gup' => '28',
          'real4Gup' => '29',
          'tab1Gup' => '30',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '75',
          'tbGup' => '31',
          'tb1Gup' => '32',
          'tb2Gup' => '33',
          'real4Gup' => '34',
          'tab1Gup' => '35',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '76',
          'tbGup' => '36',
          'tb1Gup' => '37',
          'tb2Gup' => '38',
          'real4Gup' => '39',
          'tab1Gup' => '40',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '77',
          'tbGup' => '41',
          'tb1Gup' => '42',
          'tb2Gup' => '43',
          'real4Gup' => '44',
          'tab1Gup' => '45',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '78',
          'tbGup' => '46',
          'tb1Gup' => '47',
          'tb2Gup' => '48',
          'real4Gup' => '49',
          'tab1Gup' => '50',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '79',
          'tbGup' => '51',
          'tb1Gup' => '52',
          'tb2Gup' => '53',
          'real4Gup' => '54',
          'tab1Gup' => '55',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '80',
          'tbGup' => '56',
          'tb1Gup' => '57',
          'tb2Gup' => '58',
          'real4Gup' => '59',
          'tab1Gup' => '60',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '81',
          'tbGup' => '61',
          'tb1Gup' => '62',
          'tb2Gup' => '63',
          'real4Gup' => '64',
          'tab1Gup' => '65',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '82',
          'tbGup' => '66',
          'tb1Gup' => '67',
          'tb2Gup' => '68',
          'real4Gup' => '69',
          'tab1Gup' => '70',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '83',
          'tbGup' => '71',
          'tb1Gup' => '72',
          'tb2Gup' => '73',
          'real4Gup' => '74',
          'tab1Gup' => '75',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '84',
          'tbGup' => '76',
          'tb1Gup' => '77',
          'tb2Gup' => '78',
          'real4Gup' => '79',
          'tab1Gup' => '80',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '85',
          'tbGup' => '81',
          'tb1Gup' => '82',
          'tb2Gup' => '83',
          'real4Gup' => '84',
          'tab1Gup' => '85',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '86',
          'tbGup' => '1',
          'tb1Gup' => '2',
          'tb2Gup' => '3',
          'real4Gup' => '4',
          'tab1Gup' => '5',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '87',
          'tbGup' => '6',
          'tb1Gup' => '7',
          'tb2Gup' => '8',
          'real4Gup' => '9',
          'tab1Gup' => '10',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '88',
          'tbGup' => '11',
          'tb1Gup' => '12',
          'tb2Gup' => '13',
          'real4Gup' => '14',
          'tab1Gup' => '15',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '89',
          'tbGup' => '16',
          'tb1Gup' => '17',
          'tb2Gup' => '18',
          'real4Gup' => '19',
          'tab1Gup' => '20',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '90',
          'tbGup' => '21',
          'tb1Gup' => '22',
          'tb2Gup' => '23',
          'real4Gup' => '24',
          'tab1Gup' => '25',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '91',
          'tbGup' => '26',
          'tb1Gup' => '27',
          'tb2Gup' => '28',
          'real4Gup' => '29',
          'tab1Gup' => '30',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '92',
          'tbGup' => '31',
          'tb1Gup' => '32',
          'tb2Gup' => '33',
          'real4Gup' => '34',
          'tab1Gup' => '35',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '93',
          'tbGup' => '36',
          'tb1Gup' => '37',
          'tb2Gup' => '38',
          'real4Gup' => '39',
          'tab1Gup' => '40',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '94',
          'tbGup' => '41',
          'tb1Gup' => '42',
          'tb2Gup' => '43',
          'real4Gup' => '44',
          'tab1Gup' => '45',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '95',
          'tbGup' => '46',
          'tb1Gup' => '47',
          'tb2Gup' => '48',
          'real4Gup' => '49',
          'tab1Gup' => '50',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '96',
          'tbGup' => '51',
          'tb1Gup' => '52',
          'tb2Gup' => '53',
          'real4Gup' => '54',
          'tab1Gup' => '55',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '97',
          'tbGup' => '56',
          'tb1Gup' => '57',
          'tb2Gup' => '58',
          'real4Gup' => '59',
          'tab1Gup' => '60',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '98',
          'tbGup' => '61',
          'tb1Gup' => '62',
          'tb2Gup' => '63',
          'real4Gup' => '64',
          'tab1Gup' => '65',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '99',
          'tbGup' => '66',
          'tb1Gup' => '67',
          'tb2Gup' => '68',
          'real4Gup' => '69',
          'tab1Gup' => '70',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
      Guiaproduccion::create([
          'semanaGup' => '100',
          'tbGup' => '71',
          'tb1Gup' => '72',
          'tb2Gup' => '73',
          'real4Gup' => '74',
          'tab1Gup' => '75',
          'real5Gup' => '1',
          'tab2Gup' => '2',
          'prodtbGup' => '3',
          'haatabGup' => '4',
          'grtbGup' => '5',
          'pesohuevotablaGup' => '1',
          'idGuia' => 2,
      ]);
    }
}
